"""Add client_temp_id to logbook, expenses, and deposits

Revision ID: 12a376fa962e
Revises: 215ebd043f3c
Create Date: 2025-10-12 06:54:36.875992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a376fa962e'
down_revision: Union[str, Sequence[str], None] = '215ebd043f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('client_temp_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_deposits_client_temp_id'), 'deposits', ['client_temp_id'], unique=True)
    op.add_column('expenses', sa.Column('client_temp_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_expenses_client_temp_id'), 'expenses', ['client_temp_id'], unique=True)
    op.add_column('logbook_entries', sa.Column('client_temp_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_logbook_entries_client_temp_id'), 'logbook_entries', ['client_temp_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logbook_entries_client_temp_id'), table_name='logbook_entries')
    op.drop_column('logbook_entries', 'client_temp_id')
    op.drop_index(op.f('ix_expenses_client_temp_id'), table_name='expenses')
    op.drop_column('expenses', 'client_temp_id')
    op.drop_index(op.f('ix_deposits_client_temp_id'), table_name='deposits')
    op.drop_column('deposits', 'client_temp_id')
    # ### end Alembic commands ###
