"""Add percentage split mode for expenses

Revision ID: f8d029a73997
Revises: be5598531949
Create Date: 2025-10-11 20:03:13.554189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d029a73997'
down_revision: Union[str, Sequence[str], None] = 'be5598531949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_participants', sa.Column('percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_participants', 'percentage')
    # ### end Alembic commands ###
